project_id = "gqsuujvfkgnrhvphdqqr"

[functions.create-employee-account]
verify_jwt = false

[functions.send-onboarding-email]
verify_jwt = false

[functions.sync-github-migrations]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.extract-cv-data]
enabled = true
verify_jwt = true
import_map = "./functions/extract-cv-data/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/extract-cv-data/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/extract-cv-data/*.html" ]
